plugins: &plugins
  #- docker#v5.6.0:
  #    image: python:3.10.11-slim-bullseye
  #    shell: ["/bin/bash", "-c"]
  #    user: hynso

steps:
  - label: ":python: Build first dynamic pipelines"
    key: build_first_dynamic_pipeline
    #plugins: *plugins
    commands:
      - python3 -m venv .venv
      - source .venv/bin/activate
      - python3 -m pip install --upgrade pip
      - python3 -m pip install -r requirements_1.txt
      - python3 .buildkite/scripts/build_first_dynamic_pipelines.py
      - buildkite-agent pipeline upload .buildkite/pipeline.first_dynamic_pipelines.yml
