plugins: &plugins
  - docker#v5.6.0:
      image: 3.10.11-slim-bullseye
      shell: ["/bin/bash", "-c"]
  - docker-login#v2.1.0:
      username: ldnicolasmay
      password-env: DOCKER_LOGIN_PASSWORD

steps:
  - label: ":python: Build first dynamic pipeline"
    key: build_first_dynamic_pipeline
    plugins: *plugins
    commands:
      - python3 -m venv .venv
      - source .venv/bin/activate
      - python3 -m pip install --upgrade pip
      - python3 -m pip install -r requirements.txt
      - python3 .buildkite/scripts/build_first_dynamic_pipeline.py
